### PR TITLE
Improve query performance for inserting messages

### PR DESCRIPTION
**Pull request by nuuls**
This should improve inserting performance by about 10-50x according to my testing.

Query code is kinda messy, but seems like the only way without introducing another package.

Also, I believe this fixes a bug which makes the chunk_worker loop back up over time if the message flow is above `127` messages per `config.irc.forwarder_run_every` since it calls `interval.tick().await` no matter if the buffer is full or not, and `ready_chunks(512)` only ever returns `127` items for whatever reason.

### CODE REVIEW

**Comment by RAnders00** [comment]
Yeah I noticed that thing with the 127, for the longest time I couldn‘t figure out what causes that.

that loop is meant to run every <interval> milliseconds at the very least, or faster if messages come in so fast that the buffer fills up before <interval> is over

**Comment by nuuls** [comment]
Yeah, just tested on master again to make sure, the loop runs AT MOST every interval, processing 127 messages on each run.

**Comment by RAnders00** [comment]
I'll rebase this onto `database-sharding`, I think, this looks very promising, thank you

**Comment by RAnders00** [comment]
Thanks a ton!

**Comment by nuuls** [comment]
Nice, let's see if it actually improves things

**Pull request merged**
